import type { Sound } from '../types'

const s = (id: string, name: string, category: string, icon: string, src: string, vol = 0.4): Sound => ({
  id, name, category: category as Sound['category'], icon,
  sourceType: src.startsWith('/') ? 'sample' : 'procedural',
  ...(src.startsWith('/') ? { sampleUrl: src } : { generator: src }),
  defaultVolume: vol,
})

export const sounds: Sound[] = [
  // ═══ BABY SLEEP (20) ═══
  s('lullaby-xylophone', 'Lullaby', 'baby', '🎶', '/sounds/lullaby-xylophone.mp3'),
  s('baby-harp', 'Harp Lullaby', 'baby', '🪕', '/sounds/baby-harp.mp3'),
  s('lullaby-flute', 'Flute Lullaby', 'baby', '🎵', '/sounds/lullaby-flute.mp3'),
  s('close-your-eyes', 'Close Your Eyes', 'baby', '😴', '/sounds/close-your-eyes.mp3'),
  s('my-little-star', 'My Little Star', 'baby', '⭐', '/sounds/my-little-star.mp3'),
  s('gentle-piano', 'Gentle Piano', 'baby', '🎹', '/sounds/gentle-piano.mp3'),
  s('piano-reflections', 'Piano Dreams', 'baby', '🌙', '/sounds/piano-reflections.mp3', 0.35),
  s('harp-cold-day', 'Harp Melody', 'baby', '✨', '/sounds/harp-cold-day.mp3'),
  s('gentle-guitar', 'Gentle Guitar', 'baby', '🎸', '/sounds/gentle-guitar.mp3'),
  s('flute-harp-relax', 'Flute & Harp', 'baby', '🧚', '/sounds/flute-harp-relax.mp3'),
  s('xmas-lullaby', 'Magic Lullaby', 'baby', '🎄', '/sounds/xmas-lullaby.mp3'),
  s('piano-vastness', 'Soft Piano', 'baby', '🎼', '/sounds/piano-vastness.mp3', 0.35),
  s('dreamy-piano', 'Dreamy Piano', 'baby', '💭', '/sounds/dreamy-piano.mp3', 0.35),
  s('soft-ambient', 'Soft Ambient', 'baby', '🌸', '/sounds/soft-ambient.mp3'),
  s('sleepy-harp', 'Sleepy Harp', 'baby', '💤', '/sounds/sleepy-harp.mp3'),
  s('heartbeat', 'Heartbeat', 'baby', '💓', '/sounds/heartbeat.mp3', 0.5),
  s('deep-hum', 'Deep Hum', 'baby', '🫁', '/sounds/deep-hum.mp3'),
  s('shush', 'Shushing', 'baby', '🤫', 'shush'),
  s('womb', 'Womb Sounds', 'baby', '🫶', 'womb', 0.5),
  s('baby-pink', 'Pink Noise', 'baby', '🩷', 'pink', 0.25),
  s('baby-brown', 'Brown Noise', 'baby', '🟤', 'brown', 0.25),

  // ═══ NOISE COLORS (20) ═══
  s('white-noise', 'White Noise', 'noise', '⬜', 'white', 0.3),
  s('pink-noise', 'Pink Noise', 'noise', '🩷', 'pink', 0.3),
  s('brown-noise', 'Brown Noise', 'noise', '🟤', 'brown', 0.3),
  s('green-noise', 'Green Noise', 'noise', '🟢', 'green', 0.3),
  s('gray-noise', 'Gray Noise', 'noise', '⚪', 'gray', 0.3),
  s('violet-noise', 'Violet Noise', 'noise', '🟣', 'violet', 0.25),
  s('blue-noise', 'Blue Noise', 'noise', '🔵', 'blue', 0.25),
  s('velvet-noise', 'Velvet Noise', 'noise', '🖤', 'velvet', 0.3),
  s('static-noise', 'Static', 'noise', '📺', 'static', 0.2),
  s('deep-bass', 'Deep Bass Hum', 'noise', '🔊', 'deep-bass', 0.3),
  s('warm-white', 'Warm White', 'noise', '🌤', 'warm-white', 0.3),
  s('bright-pink', 'Bright Pink', 'noise', '🌺', 'bright-pink', 0.25),
  s('dark-brown', 'Dark Brown', 'noise', '🫘', 'dark-brown', 0.3),
  s('ocean-noise', 'Ocean Noise', 'noise', '🌊', 'ocean-noise', 0.3),
  s('rain-noise', 'Rain Noise', 'noise', '🌧', 'rain-noise', 0.3),
  s('fan-noise', 'Fan', 'noise', '🌀', 'fan', 0.3),
  s('ac-noise', 'Air Conditioner', 'noise', '❄️', 'ac', 0.3),
  s('jet-noise', 'Airplane Cabin', 'noise', '✈️', 'jet', 0.25),
  s('dryer-noise', 'Dryer', 'noise', '🫧', 'dryer', 0.3),
  s('vacuum-noise', 'Vacuum', 'noise', '🧹', 'vacuum', 0.2),
  s('hiss-noise', 'Soft Hiss', 'noise', '💭', 'bright-pink', 0.2),

  // ═══ RAIN & STORM (20) ═══
  s('rain-light', 'Light Rain', 'rain', '🌧', '/sounds/rain-light.mp3', 0.6),
  s('rain-heavy', 'Heavy Rain', 'rain', '⛈', '/sounds/rain-heavy.mp3', 0.5),
  s('rain-forest', 'Forest Rain', 'rain', '🌿', '/sounds/rain-forest.mp3', 0.5),
  s('rain-loop', 'Steady Rain', 'rain', '💧', '/sounds/rain-loop.mp3', 0.5),
  s('rain-atmosphere', 'Rain Atmosphere', 'rain', '🌫', '/sounds/rain-atmosphere.mp3', 0.5),
  s('rain-metal-roof', 'Rain on Roof', 'rain', '🏠', '/sounds/rain-metal-roof.mp3', 0.5),
  s('rain-puddle', 'Rain Puddle', 'rain', '🌀', '/sounds/rain-puddle.mp3', 0.5),
  s('forest-heavy-rain', 'Forest Downpour', 'rain', '🌳', '/sounds/forest-heavy-rain.mp3', 0.5),
  s('thunder', 'Thunder', 'rain', '⚡', '/sounds/thunder.mp3'),
  s('rain-thunder-mix', 'Rain & Thunder', 'rain', '🌩', '/sounds/rain-thunder-mix.mp3'),
  s('storm-heavy', 'Heavy Storm', 'rain', '🌪', '/sounds/storm-heavy.mp3'),
  s('jungle-rain', 'Jungle Rain', 'rain', '🦜', '/sounds/jungle-rain.mp3'),
  s('thunder-jungle', 'Tropical Storm', 'rain', '🌴', '/sounds/thunder-jungle.mp3'),
  s('thunder-bg', 'Distant Thunder', 'rain', '🔊', '/sounds/thunder-bg.mp3'),
  s('thunder-rumble2', 'Thunder Rumble', 'rain', '🌑', '/sounds/thunder-rumble2.mp3'),
  s('rain-gentle', 'Gentle Drizzle', 'rain', '☁️', '/sounds/rain-light.mp3', 0.35),
  s('rain-window', 'Rain on Window', 'rain', '🪟', '/sounds/rain-atmosphere.mp3', 0.45),
  s('night-storm', 'Night Storm', 'rain', '🌃', '/sounds/storm-heavy.mp3', 0.35),
  s('spring-rain', 'Spring Rain', 'rain', '🌷', '/sounds/rain-forest.mp3', 0.45),
  s('monsoon', 'Monsoon', 'rain', '🌏', '/sounds/rain-heavy.mp3', 0.6),
  s('rain-gentle2', 'Soft Drip', 'rain', '🫧', '/sounds/rain-gentle2.mp3', 0.5),

  // ═══ WATER (20) ═══
  s('ocean-waves', 'Ocean Waves', 'water', '🌊', '/sounds/ocean-waves.mp3', 0.5),
  s('waves-close', 'Close Waves', 'water', '🏖', '/sounds/waves-close.mp3', 0.5),
  s('waves-rough', 'Rough Sea', 'water', '⛵', '/sounds/waves-rough.mp3'),
  s('waves-birds', 'Waves & Birds', 'water', '🐦', '/sounds/waves-birds.mp3'),
  s('coast-breaking', 'Breaking Coast', 'water', '🪨', '/sounds/coast-breaking.mp3'),
  s('stream', 'Flowing Stream', 'water', '💧', '/sounds/stream.mp3', 0.5),
  s('river-flowing', 'Calm River', 'water', '🏞', '/sounds/river-flowing.mp3'),
  s('river-sunrise', 'River Sunrise', 'water', '🌅', '/sounds/river-sunrise.mp3'),
  s('waterfall', 'Waterfall', 'water', '🏔', '/sounds/waterfall.mp3'),
  s('water-soft', 'Soft Water', 'water', '🫧', '/sounds/water-soft.mp3'),
  s('sea-ambience', 'Sea Ambience', 'water', '🐚', '/sounds/sea-ambience.mp3'),
  s('water-river2', 'River Flow', 'water', '🚣', '/sounds/water-river2.mp3'),
  s('waterfall-forest', 'Forest Waterfall', 'water', '🌿', '/sounds/waterfall-forest.mp3'),
  s('waterfall-ambience', 'Waterfall Mist', 'water', '💨', '/sounds/waterfall-ambience.mp3'),
  s('gentle-wave', 'Gentle Wave', 'water', '🐬', '/sounds/gentle-wave.mp3'),
  s('tide-in', 'Tide Coming In', 'water', '🌙', '/sounds/waves-close.mp3', 0.45),
  s('deep-ocean', 'Deep Ocean', 'water', '🐋', '/sounds/sea-ambience.mp3', 0.35),
  s('mountain-stream', 'Mountain Stream', 'water', '⛰', '/sounds/stream.mp3', 0.55),
  s('babbling-brook', 'Babbling Brook', 'water', '🍃', '/sounds/water-soft.mp3', 0.5),
  s('harbor-waves', 'Harbor Waves', 'water', '⚓', '/sounds/coast-breaking.mp3', 0.4),
  s('sea-coast2', 'Coastal Waves', 'water', '🏝', '/sounds/sea-coast2.mp3', 0.45),

  // ═══ NATURE (20) ═══
  s('forest', 'Morning Birds', 'nature', '🌲', '/sounds/forest.mp3'),
  s('forest-birds', 'Forest Ambience', 'nature', '🌳', '/sounds/forest-birds.mp3'),
  s('european-forest', 'European Forest', 'nature', '🍃', '/sounds/european-forest.mp3'),
  s('jungle-birds', 'Jungle Birds', 'nature', '🦜', '/sounds/jungle-birds.mp3'),
  s('crickets', 'Night Crickets', 'nature', '🦗', '/sounds/crickets.mp3'),
  s('summer-night', 'Summer Night', 'nature', '🌙', '/sounds/summer-night.mp3'),
  s('pond-crickets', 'Pond at Night', 'nature', '🐸', '/sounds/pond-crickets.mp3'),
  s('insects-wild', 'Wild Insects', 'nature', '🦟', '/sounds/insects-wild.mp3'),
  s('nature-water-birds', 'Nature Mix', 'nature', '🌿', '/sounds/nature-water-birds.mp3'),
  s('birds-river', 'Birds & River', 'nature', '🐤', '/sounds/birds-river.mp3'),
  s('morning-birds2', 'Dawn Chorus', 'nature', '🐦', '/sounds/morning-birds2.mp3'),
  s('frogs-night', 'Night Frogs', 'nature', '🐸', '/sounds/frogs-night.mp3'),
  s('crickets-long', 'Crickets Field', 'nature', '🌾', '/sounds/crickets-long.mp3'),
  s('summer-crickets2', 'Summer Cicadas', 'nature', '☀️', '/sounds/summer-crickets2.mp3'),
  s('woodland', 'Woodland', 'nature', '🦌', '/sounds/european-forest.mp3', 0.45),
  s('tropical-night', 'Tropical Night', 'nature', '🌺', '/sounds/jungle-birds.mp3', 0.4),
  s('meadow', 'Spring Meadow', 'nature', '🌼', '/sounds/nature-water-birds.mp3', 0.45),
  s('owl-night', 'Owl Night', 'nature', '🦉', '/sounds/summer-night.mp3', 0.4),
  s('garden', 'Garden Morning', 'nature', '🌻', '/sounds/birds-river.mp3', 0.45),
  s('rainforest', 'Rainforest', 'nature', '🌴', '/sounds/jungle-birds.mp3', 0.5),
  s('forest-dawn', 'Forest at Dawn', 'nature', '🌅', '/sounds/forest-dawn.mp3', 0.4),

  // ═══ WIND (20) ═══
  s('wind', 'Gentle Wind', 'wind', '💨', '/sounds/wind.mp3'),
  s('breeze-trees', 'Breeze in Trees', 'wind', '🍂', '/sounds/breeze-trees.mp3'),
  s('mountain-wind', 'Mountain Wind', 'wind', '🏔', '/sounds/mountain-wind.mp3'),
  s('winter-wind', 'Winter Wind', 'wind', '❄️', '/sounds/winter-wind.mp3'),
  s('blizzard', 'Blizzard', 'wind', '🌨', '/sounds/blizzard.mp3'),
  s('storm-wind', 'Storm Wind', 'wind', '🌀', '/sounds/storm-wind.mp3'),
  s('desert-wind', 'Desert Wind', 'wind', '🏜', '/sounds/desert-wind.mp3'),
  s('sea-humming', 'Sea Breeze', 'wind', '🐚', '/sounds/sea-humming.mp3'),
  s('wind-proc', 'Howling Wind', 'wind', '🌬', 'wind'),
  s('deep-wind', 'Deep Wind Hum', 'wind', '🎐', '/sounds/deep-hum.mp3'),
  s('wind-howl', 'Wind Howl', 'wind', '👻', '/sounds/wind-howl.mp3'),
  s('autumn-breeze', 'Autumn Breeze', 'wind', '🍁', '/sounds/breeze-trees.mp3', 0.45),
  s('arctic-wind', 'Arctic Wind', 'wind', '🧊', '/sounds/blizzard.mp3', 0.35),
  s('canyon-wind', 'Canyon Wind', 'wind', '🏜', '/sounds/mountain-wind.mp3', 0.45),
  s('coastal-gale', 'Coastal Gale', 'wind', '🌊', '/sounds/storm-wind.mp3', 0.4),
  s('night-breeze', 'Night Breeze', 'wind', '🌙', '/sounds/wind.mp3', 0.3),
  s('prairie-wind', 'Prairie Wind', 'wind', '🌾', '/sounds/desert-wind.mp3', 0.4),
  s('hilltop-wind', 'Hilltop Wind', 'wind', '⛰', '/sounds/wind-howl.mp3', 0.35),
  s('spring-breeze', 'Spring Breeze', 'wind', '🌸', '/sounds/breeze-trees.mp3', 0.35),
  s('whistling-wind', 'Whistling Wind', 'wind', '🎵', '/sounds/winter-wind.mp3', 0.4),
  s('wind-gentle2', 'Soft Gust', 'wind', '🌱', '/sounds/wind-gentle2.mp3', 0.35),

  // ═══ FIRE & RELAX (20) ═══
  s('fireplace', 'Fireplace', 'fire', '🔥', '/sounds/fireplace.mp3', 0.5),
  s('campfire-burn', 'Campfire', 'fire', '🏕', '/sounds/campfire-burn.mp3', 0.5),
  s('campfire-night', 'Night Campfire', 'fire', '🌌', '/sounds/campfire-night.mp3'),
  s('campfire-crackle2', 'Fire Crackle', 'fire', '💥', '/sounds/campfire-crackle2.mp3', 0.5),
  s('relaxing-country', 'Campfire Guitar', 'fire', '🎸', '/sounds/relaxing-country.mp3'),
  s('rest-now', 'Rest Now', 'fire', '🌙', '/sounds/rest-now.mp3'),
  s('silent-descent', 'Silent Descent', 'fire', '🕯', '/sounds/silent-descent.mp3'),
  s('wind-leaves-music', 'Wind & Leaves', 'fire', '🍂', '/sounds/wind-leaves.mp3'),
  s('meditation-fire', 'Fire Meditation', 'fire', '🧘', '/sounds/meditation.mp3'),
  s('ambient-relax', 'Deep Relax', 'fire', '😌', '/sounds/ambient-relax.mp3'),
  s('classical1', 'Piano Evening', 'fire', '🎹', '/sounds/classical1.mp3'),
  s('classical2', 'Solo Piano', 'fire', '🎼', '/sounds/classical2.mp3'),
  s('slow-pop', 'Gentle Acoustic', 'fire', '🌿', '/sounds/slow-pop.mp3'),
  s('bonfire-big', 'Bonfire', 'fire', '🪵', '/sounds/campfire-burn.mp3', 0.6),
  s('embers', 'Glowing Embers', 'fire', '🟠', '/sounds/fireplace.mp3', 0.3),
  s('cabin-fire', 'Cabin Fireplace', 'fire', '🏡', '/sounds/campfire-night.mp3', 0.45),
  s('fire-rain', 'Fire + Rain', 'fire', '🌧', '/sounds/campfire-night.mp3', 0.4),
  s('wood-stove', 'Wood Stove', 'fire', '🪵', '/sounds/campfire-crackle2.mp3', 0.4),
  s('cozy-evening', 'Cozy Evening', 'fire', '🛋', '/sounds/rest-now.mp3', 0.4),
  s('fireside-guitar', 'Fireside Guitar', 'fire', '🎶', '/sounds/relaxing-country.mp3', 0.45),
  s('warm-hearth', 'Warm Hearth', 'fire', '🧡', '/sounds/campfire-burn.mp3', 0.4),

  // ═══ URBAN (20) ═══
  s('coffee-shop', 'Coffee Shop', 'urban', '☕', '/sounds/coffee-shop.mp3', 0.3),
  s('train', 'Train Journey', 'urban', '🚂', '/sounds/train.mp3'),
  s('train-station', 'Train Station', 'urban', '🚉', '/sounds/train-station.mp3'),
  s('train-depart', 'Train Departing', 'urban', '🚄', '/sounds/train-depart.mp3'),
  s('office', 'Office Ambience', 'urban', '💼', '/sounds/office.mp3', 0.3),
  s('crowd-pub', 'Busy Pub', 'urban', '🍺', '/sounds/crowd-pub.mp3', 0.3),
  s('crowd-restaurant', 'Restaurant', 'urban', '🍽', '/sounds/crowd-restaurant.mp3', 0.3),
  s('train-rattle', 'Train Rattle', 'urban', '🛤', '/sounds/train-rattle.mp3'),
  s('train-old2', 'Vintage Train', 'urban', '🚃', '/sounds/train-old2.mp3'),
  s('vastness-urban', 'Rainy Window', 'urban', '🪟', '/sounds/vastness.mp3'),
  s('morning-cafe', 'Morning Cafe', 'urban', '🥐', '/sounds/coffee-shop.mp3', 0.35),
  s('subway', 'Subway', 'urban', '🚇', '/sounds/train-rattle.mp3', 0.35),
  s('library', 'Library', 'urban', '📚', '/sounds/office.mp3', 0.2),
  s('coworking', 'Coworking Space', 'urban', '💻', '/sounds/office.mp3', 0.25),
  s('night-train', 'Night Train', 'urban', '🌃', '/sounds/train.mp3', 0.35),
  s('rainy-street', 'Rainy Street', 'urban', '☔', '/sounds/rain-atmosphere.mp3', 0.4),
  s('busy-market', 'Busy Market', 'urban', '🛒', '/sounds/crowd-pub.mp3', 0.35),
  s('bookshop', 'Bookshop', 'urban', '📖', '/sounds/crowd-restaurant.mp3', 0.2),
  s('late-night-cafe', 'Late Night Cafe', 'urban', '🌙', '/sounds/crowd-restaurant.mp3', 0.25),
  s('hotel-lobby', 'Hotel Lobby', 'urban', '🏨', '/sounds/office.mp3', 0.3),
  s('airport-lounge', 'Airport Lounge', 'urban', '✈️', '/sounds/crowd-restaurant.mp3', 0.3),

  // ═══ COSMOS (20) ═══
  s('cosmic-drone', 'Cosmic Drone', 'cosmos', '🪐', '/sounds/cosmic-drone.mp3', 0.3),
  s('scifi-ambient', 'Sci-Fi Ambient', 'cosmos', '🛸', '/sounds/scifi-ambient.mp3', 0.3),
  s('mystery-pulse', 'Deep Space Pulse', 'cosmos', '💫', '/sounds/mystery-pulse.mp3', 0.3),
  s('valley-sunset', 'Nebula Drift', 'cosmos', '🌌', '/sounds/valley-sunset.mp3', 0.3),
  s('nature-meditation', 'Star Meditation', 'cosmos', '⭐', '/sounds/nature-meditation.mp3', 0.3),
  s('solar-wind', 'Solar Wind', 'cosmos', '☀️', 'solar-wind', 0.3),
  s('pulsar', 'Pulsar', 'cosmos', '🌟', 'pulsar', 0.2),
  s('space-synth', 'Space Synth', 'cosmos', '🎹', '/sounds/space-synth.mp3', 0.3),
  s('cosmic-piano', 'Cosmic Piano', 'cosmos', '🎼', '/sounds/cosmic-piano.mp3', 0.3),
  s('ethereal', 'Ethereal', 'cosmos', '🔮', '/sounds/ethereal.mp3', 0.3),
  s('cosmic-hum', 'Cosmic Hum', 'cosmos', '📡', '/sounds/deep-hum.mp3', 0.3),
  s('event-horizon', 'Event Horizon', 'cosmos', '🕳', '/sounds/sea-humming.mp3', 0.25),
  s('aurora', 'Aurora', 'cosmos', '🌈', '/sounds/ethereal.mp3', 0.35),
  s('saturn-rings', 'Saturn Rings', 'cosmos', '🪐', '/sounds/cosmic-drone.mp3', 0.25),
  s('deep-void', 'Deep Void', 'cosmos', '⬛', '/sounds/scifi-ambient.mp3', 0.2),
  s('stellar-wind', 'Stellar Wind', 'cosmos', '💨', '/sounds/valley-sunset.mp3', 0.3),
  s('galaxy-hum', 'Galaxy Hum', 'cosmos', '🌀', '/sounds/deep-hum.mp3', 0.25),
  s('nebula-glow', 'Nebula Glow', 'cosmos', '✨', '/sounds/space-synth.mp3', 0.3),
  s('warp-drive', 'Warp Drive', 'cosmos', '🚀', '/sounds/mystery-pulse.mp3', 0.25),
  s('starlight', 'Starlight', 'cosmos', '🌠', '/sounds/cosmic-piano.mp3', 0.3),
  s('black-hole', 'Black Hole', 'cosmos', '⚫', '/sounds/mystery-pulse.mp3', 0.2),

  // ═══ BINAURAL BEATS (20) ═══
  s('binaural-delta', 'Delta 2Hz', 'binaural', '🌀', 'binaural-delta', 0.2),
  s('binaural-delta3', 'Delta 3Hz', 'binaural', '💤', 'binaural-delta3', 0.2),
  s('binaural-theta4', 'Theta 4Hz', 'binaural', '🌙', 'binaural-theta4', 0.2),
  s('binaural-theta5', 'Theta 5Hz', 'binaural', '🌊', 'binaural-theta5', 0.2),
  s('binaural-theta', 'Theta 6Hz', 'binaural', '😌', 'binaural-theta', 0.2),
  s('binaural-theta7', 'Theta 7Hz', 'binaural', '🎭', 'binaural-theta7', 0.2),
  s('binaural-theta8', 'Theta 8Hz', 'binaural', '🧘', 'binaural-theta8', 0.2),
  s('binaural-alpha9', 'Alpha 9Hz', 'binaural', '🌸', 'binaural-alpha9', 0.2),
  s('binaural-alpha', 'Alpha 10Hz', 'binaural', '✨', 'binaural-alpha', 0.2),
  s('binaural-alpha11', 'Alpha 11Hz', 'binaural', '🌿', 'binaural-alpha11', 0.2),
  s('binaural-alpha12', 'Alpha 12Hz', 'binaural', '☀️', 'binaural-alpha12', 0.2),
  s('binaural-alpha13', 'Alpha 13Hz', 'binaural', '🌈', 'binaural-alpha13', 0.2),
  s('binaural-beta', 'Beta 15Hz', 'binaural', '🎯', 'binaural-beta', 0.2),
  s('binaural-beta18', 'Beta 18Hz', 'binaural', '📐', 'binaural-beta18', 0.2),
  s('binaural-beta20', 'Beta 20Hz', 'binaural', '⚡', 'binaural-beta20', 0.2),
  s('binaural-beta25', 'Beta 25Hz', 'binaural', '💡', 'binaural-beta25', 0.2),
  s('binaural-gamma', 'Gamma 30Hz', 'binaural', '🧠', 'binaural-gamma30', 0.15),
  s('binaural-gamma35', 'Gamma 35Hz', 'binaural', '🔬', 'binaural-gamma35', 0.15),
  s('binaural-gamma40', 'Gamma 40Hz', 'binaural', '⚛️', 'binaural-gamma40', 0.15),
  s('binaural-schumann', 'Schumann 7.83Hz', 'binaural', '🌍', 'binaural-schumann', 0.2),
  s('binaural-deep1', 'Deep 1Hz', 'binaural', '🔷', 'binaural-deep1', 0.15),
]

export const categories: { id: string; name: string; icon: string }[] = [
  { id: 'baby', name: 'Baby Sleep', icon: '👶' },
  { id: 'noise', name: 'Noise Colors', icon: '🎛' },
  { id: 'rain', name: 'Rain & Storm', icon: '🌧' },
  { id: 'water', name: 'Water', icon: '🌊' },
  { id: 'nature', name: 'Nature', icon: '🌲' },
  { id: 'wind', name: 'Wind', icon: '💨' },
  { id: 'fire', name: 'Fire & Relax', icon: '🔥' },
  { id: 'urban', name: 'Urban', icon: '🏙' },
  { id: 'cosmos', name: 'Cosmos', icon: '🪐' },
  { id: 'binaural', name: 'Binaural Beats', icon: '🧠' },
]

export function getSoundById(id: string): Sound | undefined {
  return sounds.find((s) => s.id === id)
}

export function getSoundsByCategory(category: string): Sound[] {
  return sounds.filter((s) => s.category === category)
}
