import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'en' | 'ro' | 'ru' | 'es'
export type ThemeMode = 'dark' | 'midnight' | 'amoled' | 'ocean'

export interface ThemeColors {
  bgPrimary: string
  bgSecondary: string
  bgCard: string
  bgCardHover: string
  bgActive: string
  accent: string
  accentGlow: string
  accentLight: string
}

export const themes: Record<ThemeMode, ThemeColors> = {
  dark: {
    bgPrimary: '#0a0a1a',
    bgSecondary: '#111128',
    bgCard: '#181838',
    bgCardHover: '#1f1f48',
    bgActive: '#2a1a5e',
    accent: '#7c5cfc',
    accentGlow: 'rgba(124, 92, 252, 0.3)',
    accentLight: '#9d82ff',
  },
  midnight: {
    bgPrimary: '#0d1117',
    bgSecondary: '#161b22',
    bgCard: '#1c2333',
    bgCardHover: '#252d3d',
    bgActive: '#1a3a5c',
    accent: '#58a6ff',
    accentGlow: 'rgba(88, 166, 255, 0.3)',
    accentLight: '#79c0ff',
  },
  amoled: {
    bgPrimary: '#000000',
    bgSecondary: '#0a0a0a',
    bgCard: '#141414',
    bgCardHover: '#1e1e1e',
    bgActive: '#1a1a3a',
    accent: '#bb86fc',
    accentGlow: 'rgba(187, 134, 252, 0.3)',
    accentLight: '#d4a5ff',
  },
  ocean: {
    bgPrimary: '#0a1628',
    bgSecondary: '#0f1d32',
    bgCard: '#152640',
    bgCardHover: '#1c3050',
    bgActive: '#1a3d5c',
    accent: '#00b4d8',
    accentGlow: 'rgba(0, 180, 216, 0.3)',
    accentLight: '#48cae4',
  },
}

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.tagline': 'drift into dreams',
    'nav.sounds': 'Sounds',
    'nav.mixes': 'Mixes',
    'nav.breathe': 'Breathe',
    'nav.settings': 'Settings',
    'sounds.all': 'All',
    'cat.noise': 'Noise Colors',
    'cat.rain': 'Rain & Storm',
    'cat.water': 'Water',
    'cat.nature': 'Nature',
    'cat.wind': 'Wind',
    'cat.fire': 'Fire',
    'cat.urban': 'Urban',
    'cat.cosmos': 'Cosmos',
    'cat.baby': 'Baby Sleep',
    'cat.binaural': 'Binaural Beats',
    'player.playing': 'playing',
    'player.sound': 'sound',
    'player.sounds': 'sounds',
    'timer.title': 'Sleep Timer',
    'timer.fadeout': 'Fade out',
    'timer.cancel': 'Cancel Timer',
    'timer.fadingout': 'Fading out in the last',
    'mixes.title': 'My Mixes',
    'mixes.save': 'Save Current',
    'mixes.saveCurrent': 'Save Current Mix',
    'mixes.empty': 'No saved mixes yet',
    'mixes.emptyHint': 'Play some sounds and save your favorite combinations',
    'mixes.placeholder': 'Mix name...',
    'mixes.saveBtn': 'Save',
    'breathing.title': 'Breathing',
    'breathing.desc': 'Guided breathing exercises to help you relax and fall asleep.',
    'breathing.start': 'Start',
    'breathing.stop': 'Stop',
    'breathing.back': 'Back',
    'breathing.ready': 'Ready',
    'breathing.inhale': 'Inhale',
    'breathing.hold': 'Hold',
    'breathing.exhale': 'Exhale',
    'breathing.cycles': 'cycles completed',
    'breathing.cycle': 'cycle completed',
    'breathing.478': '4-7-8 Relaxing',
    'breathing.478.desc': 'Calms the nervous system, promotes sleep',
    'breathing.box': 'Box Breathing',
    'breathing.box.desc': 'Reduces stress and anxiety',
    'breathing.simple': 'Simple Calm',
    'breathing.simple.desc': 'Easy breathing for beginners',
    'breathing.coherent': 'Coherent',
    'breathing.coherent.desc': 'Heart-brain coherence at 6 breaths/min',
    'breathing.session': 'Session',
    'breathing.minutes': 'minutes',
    'breathing.infinite': 'Infinite',
    'breathing.custom': 'Custom',
    'breathing.custom.desc': 'Set your own rhythm',
    'breathing.complete': 'Session Complete',
    'breathing.totalTime': 'Total time',
    'breathing.sounds': 'Ambient Sound',
    'breathing.silent': 'Silent',
    'breathing.breatheIn': 'Breathe In',
    'breathing.breatheOut': 'Breathe Out',
    'breathing.zenScene': 'Zen Temple',
    'breathing.warmScene': 'Warm Drift',
    'breathing.meditationScene': 'Meditation',
    'random.title': 'Random Mix',
    'random.count': 'Number of sounds',
    'random.volumeMin': 'Min volume',
    'random.volumeMax': 'Max volume',
    'random.categories': 'Categories',
    'random.diversify': 'Different categories',
    'random.generate': 'Generate Mix',
    'random.presets': 'Quick Presets',
    'random.preset.deepSleep': 'Deep Sleep',
    'random.preset.natureRelax': 'Nature Relax',
    'random.preset.focus': 'Focus',
    'random.preset.cozy': 'Cozy',
    'random.enableAll': 'Enable All',
    'sounds.search': 'Search sounds...',
    'sounds.noResults': 'No sounds found',
    'sounds.favorites': 'Favorites',
    'settings.binaural': 'Binaural Beats',
    'settings.binaural.desc': 'Show binaural beats category',
    'sounds.allSounds': 'All Sounds',
    'exit.message': 'Are you sure you want to leave Somnio?',
    'exit.stay': 'Stay',
    'exit.leave': 'Leave',
    'start.timer': 'Start Timer',
    'settings.howToUse': 'How to use',
    'howto.mix.title': 'Mix sounds',
    'howto.mix.desc': 'Tap any card to play. Tap multiple cards to mix sounds together.',
    'howto.volume.title': 'Adjust volume',
    'howto.volume.desc': 'Use the vertical slider on each card, or tap the player bar to expand the mixer.',
    'howto.save.title': 'Save mixes',
    'howto.save.desc': 'Tap the bookmark icon in the player bar to save your current mix.',
    'howto.timer.title': 'Sleep timer',
    'howto.timer.desc': 'Tap the clock icon in the top right. Set duration and sounds will fade out automatically.',
    'howto.breathe.title': 'Breathing exercises',
    'howto.breathe.desc': 'Go to the Breathe tab. Choose a pattern and follow the animated circle.',
    'howto.info.title': 'Sound info',
    'howto.info.desc': 'Tap the "i" button on any card to see details, tips, and adjust volume.',
    'howto.install.title': 'Install as app',
    'howto.install.desc.android': 'Android: Open in Chrome > Menu (3 dots) > "Install app" or "Add to Home screen".',
    'howto.install.desc.ios': 'iPhone: Open in Safari > Tap Share button > "Add to Home Screen".',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.theme.dark': 'Dark',
    'settings.theme.midnight': 'Midnight',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Ocean',
    'settings.about': 'About',
    'settings.version': 'Version',
    'settings.donate': 'Support Somnio',
    'settings.donateDesc': 'Somnio is free and open. If you enjoy it, consider a donation.',
    'install': 'Install App',
    'scenes.title': 'Scenes',
    'scene.zenTemple': 'Zen Temple',
    'scene.zenTemple.desc': 'Singing bowls and temple bells',
    'scene.rainyNight': 'Rainy Night',
    'scene.rainyNight.desc': 'Heavy rain with distant thunder',
    'scene.forestClearing': 'Forest Clearing',
    'scene.forestClearing.desc': 'Night insects and flowing water',
    'scene.cozyCabin': 'Cozy Cabin',
    'scene.cozyCabin.desc': 'Fireplace with rain outside',
    'scene.deepOcean': 'Deep Ocean',
    'scene.deepOcean.desc': 'Underwater ambience',
    'scene.warmDrift': 'Warm Drift',
    'scene.warmDrift.desc': 'Soft noise with gentle chimes',
    'scene.tibetanEvening': 'Tibetan Evening',
    'scene.tibetanEvening.desc': 'Om drone with singing bowls',
    'scene.starfield': 'Starfield',
    'scene.starfield.desc': 'Cosmic drones and ethereal tones',
    'scene.meditation': 'Meditation',
    'scene.meditation.desc': 'Om drone with singing bowls and ambient pad',
    'scene.cafeFocus': 'Café Focus',
    'scene.cafeFocus.desc': 'Coffee shop ambience with gentle rain',
    'scene.nightTrain': 'Night Train',
    'scene.nightTrain.desc': 'Train journey through the rain',
    'scene.beachSunset': 'Beach Sunset',
    'scene.beachSunset.desc': 'Ocean waves with evening crickets',
    'scene.candlelight': 'Candlelight',
    'scene.candlelight.desc': 'Warm fireplace with soft chimes',
    'scene.babySleep': 'Baby Sleep',
    'scene.babySleep.desc': 'Womb sounds with heartbeat',
  },
  ro: {
    'app.tagline': 'pluteste in vise',
    'nav.sounds': 'Sunete',
    'nav.mixes': 'Mix-uri',
    'nav.breathe': 'Respiratie',
    'nav.settings': 'Setari',
    'sounds.all': 'Toate',
    'cat.noise': 'Culori Zgomot',
    'cat.rain': 'Ploaie & Furtuna',
    'cat.water': 'Apa',
    'cat.nature': 'Natura',
    'cat.wind': 'Vant',
    'cat.fire': 'Foc',
    'cat.urban': 'Urban',
    'cat.cosmos': 'Cosmos',
    'cat.baby': 'Somn Bebelusi',
    'cat.binaural': 'Unde Binaurale',
    'player.playing': 'redam',
    'player.sound': 'sunet',
    'player.sounds': 'sunete',
    'timer.title': 'Timer Somn',
    'timer.fadeout': 'Diminuare',
    'timer.cancel': 'Anuleaza Timer',
    'timer.fadingout': 'Se diminueaza in ultimele',
    'mixes.title': 'Mix-urile Mele',
    'mixes.save': 'Salveaza',
    'mixes.saveCurrent': 'Salveaza Mixul Curent',
    'mixes.empty': 'Niciun mix salvat',
    'mixes.emptyHint': 'Reda sunete si salveaza combinatiile preferate',
    'mixes.placeholder': 'Numele mix-ului...',
    'mixes.saveBtn': 'Salveaza',
    'breathing.title': 'Respiratie',
    'breathing.desc': 'Exercitii de respiratie ghidate pentru relaxare si adormire.',
    'breathing.start': 'Start',
    'breathing.stop': 'Stop',
    'breathing.back': 'Inapoi',
    'breathing.ready': 'Pregatit',
    'breathing.inhale': 'Inspira',
    'breathing.hold': 'Tine',
    'breathing.exhale': 'Expira',
    'breathing.cycles': 'cicluri completate',
    'breathing.cycle': 'ciclu completat',
    'breathing.478': '4-7-8 Relaxare',
    'breathing.478.desc': 'Calmeaza sistemul nervos, promoveaza somnul',
    'breathing.box': 'Respiratie Box',
    'breathing.box.desc': 'Reduce stresul si anxietatea',
    'breathing.simple': 'Calm Simplu',
    'breathing.simple.desc': 'Respiratie usoara pentru incepatori',
    'breathing.coherent': 'Coherenta',
    'breathing.coherent.desc': 'Coherenta inima-creier la 6 respiratii/min',
    'breathing.session': 'Sesiune',
    'breathing.minutes': 'minute',
    'breathing.infinite': 'Infinit',
    'breathing.custom': 'Personalizat',
    'breathing.custom.desc': 'Seteaza-ti propriul ritm',
    'breathing.complete': 'Sesiune Completa',
    'breathing.totalTime': 'Timp total',
    'breathing.sounds': 'Sunet Ambient',
    'breathing.silent': 'Liniste',
    'breathing.breatheIn': 'Inspira',
    'breathing.breatheOut': 'Expira',
    'breathing.zenScene': 'Templul Zen',
    'breathing.warmScene': 'Plutire Calda',
    'breathing.meditationScene': 'Meditatie',
    'random.title': 'Mix Aleator',
    'random.count': 'Numar de sunete',
    'random.volumeMin': 'Volum minim',
    'random.volumeMax': 'Volum maxim',
    'random.categories': 'Categorii',
    'random.diversify': 'Categorii diferite',
    'random.generate': 'Genereaza Mix',
    'random.presets': 'Preset-uri Rapide',
    'random.preset.deepSleep': 'Somn Profund',
    'random.preset.natureRelax': 'Natura Relaxanta',
    'random.preset.focus': 'Concentrare',
    'random.preset.cozy': 'Confort',
    'random.enableAll': 'Activeaza Toate',
    'sounds.search': 'Cauta sunete...',
    'sounds.noResults': 'Niciun sunet gasit',
    'sounds.favorites': 'Favorite',
    'settings.binaural': 'Frecvente Binaurale',
    'settings.binaural.desc': 'Afiseaza categoria frecvente binaurale',
    'sounds.allSounds': 'Toate Sunetele',
    'exit.message': 'Esti sigur ca vrei sa parasesti Somnio?',
    'exit.stay': 'Raman',
    'exit.leave': 'Ies',
    'start.timer': 'Porneste Timer',
    'settings.howToUse': 'Cum se foloseste',
    'howto.mix.title': 'Mixeaza sunete',
    'howto.mix.desc': 'Apasa orice card pentru a reda. Apasa mai multe carduri pentru a mixa sunete.',
    'howto.volume.title': 'Regleaza volumul',
    'howto.volume.desc': 'Foloseste sliderul vertical de pe card, sau apasa pe player bar pentru mixer.',
    'howto.save.title': 'Salveaza mix-uri',
    'howto.save.desc': 'Apasa iconita bookmark din player bar pentru a salva mix-ul curent.',
    'howto.timer.title': 'Timer de somn',
    'howto.timer.desc': 'Apasa iconita ceas din dreapta sus. Seteaza durata si sunetele se vor diminua automat.',
    'howto.breathe.title': 'Exercitii de respiratie',
    'howto.breathe.desc': 'Mergi la tab-ul Respiratie. Alege un model si urmeaza cercul animat.',
    'howto.info.title': 'Info sunet',
    'howto.info.desc': 'Apasa butonul "i" pe orice card pentru detalii, sfaturi si reglaj volum.',
    'howto.install.title': 'Instaleaza ca aplicatie',
    'howto.install.desc.android': 'Android: Deschide in Chrome > Meniu (3 puncte) > "Instaleaza aplicatia" sau "Adauga pe ecranul principal".',
    'howto.install.desc.ios': 'iPhone: Deschide in Safari > Apasa butonul Share > "Adauga pe ecranul principal".',
    'settings.title': 'Setari',
    'settings.language': 'Limba',
    'settings.theme': 'Tema',
    'settings.theme.dark': 'Intuneric',
    'settings.theme.midnight': 'Miezul Noptii',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Ocean',
    'settings.about': 'Despre',
    'settings.version': 'Versiune',
    'settings.donate': 'Sustine Somnio',
    'settings.donateDesc': 'Somnio e gratuit si deschis. Daca iti place, considera o donatie.',
    'install': 'Instaleaza',
    'scenes.title': 'Scene',
    'scene.zenTemple': 'Templul Zen',
    'scene.zenTemple.desc': 'Boluri tibetane si clopote',
    'scene.rainyNight': 'Noapte Ploioasa',
    'scene.rainyNight.desc': 'Ploaie cu tunete in departare',
    'scene.forestClearing': 'Poiana Padurii',
    'scene.forestClearing.desc': 'Insecte de noapte si apa curgatoare',
    'scene.cozyCabin': 'Cabana Confortabila',
    'scene.cozyCabin.desc': 'Semineu cu ploaie afara',
    'scene.deepOcean': 'Ocean Profund',
    'scene.deepOcean.desc': 'Atmosfera subacvatica',
    'scene.warmDrift': 'Plutire Calda',
    'scene.warmDrift.desc': 'Zgomot bland cu clopotei',
    'scene.tibetanEvening': 'Seara Tibetana',
    'scene.tibetanEvening.desc': 'Drone om cu boluri tibetane',
    'scene.starfield': 'Camp Stelar',
    'scene.starfield.desc': 'Drone-uri cosmice si tonuri eterice',
    'scene.meditation': 'Meditatie',
    'scene.meditation.desc': 'Drone om cu boluri tibetane si pad ambient',
    'scene.cafeFocus': 'Cafenea Focus',
    'scene.cafeFocus.desc': 'Atmosfera de cafenea cu ploaie usoara',
    'scene.nightTrain': 'Tren de Noapte',
    'scene.nightTrain.desc': 'Calatorie cu trenul prin ploaie',
    'scene.beachSunset': 'Apus pe Plaja',
    'scene.beachSunset.desc': 'Valuri de ocean cu greieri de seara',
    'scene.candlelight': 'Lumanare',
    'scene.candlelight.desc': 'Semineu cald cu clopotei subtili',
    'scene.babySleep': 'Somn Bebe',
    'scene.babySleep.desc': 'Sunete de uter cu batai de inima',
  },
  ru: {
    'app.tagline': 'погрузись в сны',
    'nav.sounds': 'Звуки',
    'nav.mixes': 'Миксы',
    'nav.breathe': 'Дыхание',
    'nav.settings': 'Настройки',
    'sounds.all': 'Все',
    'cat.noise': 'Цвета шума',
    'cat.rain': 'Дождь и гроза',
    'cat.water': 'Вода',
    'cat.nature': 'Природа',
    'cat.wind': 'Ветер',
    'cat.fire': 'Огонь',
    'cat.urban': 'Город',
    'cat.cosmos': 'Космос',
    'cat.baby': 'Сон малыша',
    'cat.binaural': 'Бинауральные',
    'player.playing': 'воспроизводится',
    'player.sound': 'звук',
    'player.sounds': 'звуков',
    'timer.title': 'Таймер сна',
    'timer.fadeout': 'Затухание',
    'timer.cancel': 'Отменить таймер',
    'timer.fadingout': 'Затухание в последние',
    'mixes.title': 'Мои миксы',
    'mixes.save': 'Сохранить',
    'mixes.saveCurrent': 'Сохранить текущий микс',
    'mixes.empty': 'Нет сохранённых миксов',
    'mixes.emptyHint': 'Включите звуки и сохраните любимые комбинации',
    'mixes.placeholder': 'Название микса...',
    'mixes.saveBtn': 'Сохранить',
    'breathing.title': 'Дыхание',
    'breathing.desc': 'Дыхательные упражнения для расслабления и засыпания.',
    'breathing.start': 'Старт',
    'breathing.stop': 'Стоп',
    'breathing.back': 'Назад',
    'breathing.ready': 'Готов',
    'breathing.inhale': 'Вдох',
    'breathing.hold': 'Задержка',
    'breathing.exhale': 'Выдох',
    'breathing.cycles': 'циклов завершено',
    'breathing.cycle': 'цикл завершён',
    'breathing.478': '4-7-8 Расслабление',
    'breathing.478.desc': 'Успокаивает нервную систему, помогает уснуть',
    'breathing.box': 'Квадратное дыхание',
    'breathing.box.desc': 'Снижает стресс и тревогу',
    'breathing.simple': 'Простое спокойствие',
    'breathing.simple.desc': 'Лёгкое дыхание для начинающих',
    'breathing.coherent': 'Когерентное',
    'breathing.coherent.desc': 'Когерентность сердце-мозг при 6 вдохах/мин',
    'breathing.session': 'Сессия',
    'breathing.minutes': 'минут',
    'breathing.infinite': 'Бесконечно',
    'breathing.custom': 'Свой',
    'breathing.custom.desc': 'Задайте свой ритм',
    'breathing.complete': 'Сессия завершена',
    'breathing.totalTime': 'Общее время',
    'breathing.sounds': 'Фоновый звук',
    'breathing.silent': 'Тишина',
    'breathing.breatheIn': 'Вдох',
    'breathing.breatheOut': 'Выдох',
    'breathing.zenScene': 'Дзен храм',
    'breathing.warmScene': 'Тёплый дрейф',
    'breathing.meditationScene': 'Медитация',
    'random.title': 'Случайный микс',
    'random.count': 'Количество звуков',
    'random.volumeMin': 'Мин. громкость',
    'random.volumeMax': 'Макс. громкость',
    'random.categories': 'Категории',
    'random.diversify': 'Разные категории',
    'random.generate': 'Сгенерировать микс',
    'random.presets': 'Быстрые пресеты',
    'random.preset.deepSleep': 'Глубокий сон',
    'random.preset.natureRelax': 'Природа',
    'random.preset.focus': 'Фокус',
    'random.preset.cozy': 'Уют',
    'random.enableAll': 'Включить все',
    'sounds.search': 'Поиск звуков...',
    'sounds.noResults': 'Звуки не найдены',
    'sounds.favorites': 'Избранные',
    'settings.binaural': 'Бинауральные ритмы',
    'settings.binaural.desc': 'Показывать категорию бинауральных ритмов',
    'sounds.allSounds': 'Все звуки',
    'exit.message': 'Вы уверены, что хотите выйти из Somnio?',
    'exit.stay': 'Остаться',
    'exit.leave': 'Выйти',
    'start.timer': 'Запустить таймер',
    'settings.howToUse': 'Как пользоваться',
    'howto.mix.title': 'Микшируйте звуки',
    'howto.mix.desc': 'Нажмите на карточку для воспроизведения. Нажмите несколько для микширования.',
    'howto.volume.title': 'Регулируйте громкость',
    'howto.volume.desc': 'Используйте вертикальный слайдер на карточке или нажмите на плеер для микшера.',
    'howto.save.title': 'Сохраняйте миксы',
    'howto.save.desc': 'Нажмите закладку в плеере, чтобы сохранить текущий микс.',
    'howto.timer.title': 'Таймер сна',
    'howto.timer.desc': 'Нажмите часы в правом верхнем углу. Установите время и звуки затихнут автоматически.',
    'howto.breathe.title': 'Дыхательные упражнения',
    'howto.breathe.desc': 'Перейдите на вкладку Дыхание. Выберите паттерн и следуйте анимированному кругу.',
    'howto.info.title': 'Информация о звуке',
    'howto.info.desc': 'Нажмите "i" на карточке для описания, советов и регулировки громкости.',
    'howto.install.title': 'Установить как приложение',
    'howto.install.desc.android': 'Android: Откройте в Chrome > Меню (3 точки) > "Установить приложение" или "На главный экран".',
    'howto.install.desc.ios': 'iPhone: Откройте в Safari > Кнопка "Поделиться" > "На экран Домой".',
    'settings.title': 'Настройки',
    'settings.language': 'Язык',
    'settings.theme': 'Тема',
    'settings.theme.dark': 'Тёмная',
    'settings.theme.midnight': 'Полночь',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Океан',
    'settings.about': 'О приложении',
    'settings.version': 'Версия',
    'settings.donate': 'Поддержать Somnio',
    'settings.donateDesc': 'Somnio бесплатен и открыт. Если нравится, поддержите донатом.',
    'install': 'Установить',
    'scenes.title': 'Сцены',
    'scene.zenTemple': 'Дзен храм',
    'scene.zenTemple.desc': 'Поющие чаши и колокола',
    'scene.rainyNight': 'Дождливая ночь',
    'scene.rainyNight.desc': 'Дождь с далёким громом',
    'scene.forestClearing': 'Лесная поляна',
    'scene.forestClearing.desc': 'Ночные звуки и ручей',
    'scene.cozyCabin': 'Уютная хижина',
    'scene.cozyCabin.desc': 'Камин и дождь за окном',
    'scene.deepOcean': 'Глубокий океан',
    'scene.deepOcean.desc': 'Подводная атмосфера',
    'scene.warmDrift': 'Тёплый дрейф',
    'scene.warmDrift.desc': 'Мягкий шум с нежными колокольчиками',
    'scene.tibetanEvening': 'Тибетский вечер',
    'scene.tibetanEvening.desc': 'Ом дрон с поющими чашами',
    'scene.starfield': 'Звёздное поле',
    'scene.starfield.desc': 'Космические дроны',
    'scene.meditation': 'Медитация',
    'scene.meditation.desc': 'Ом дрон с поющими чашами и пэдом',
    'scene.cafeFocus': 'Кафе Фокус',
    'scene.cafeFocus.desc': 'Атмосфера кафе с лёгким дождём',
    'scene.nightTrain': 'Ночной Поезд',
    'scene.nightTrain.desc': 'Поездка на поезде под дождём',
    'scene.beachSunset': 'Закат на Пляже',
    'scene.beachSunset.desc': 'Океанские волны с вечерними сверчками',
    'scene.candlelight': 'Свечи',
    'scene.candlelight.desc': 'Тёплый камин с нежными колокольчиками',
    'scene.babySleep': 'Сон Малыша',
    'scene.babySleep.desc': 'Звуки утробы с сердцебиением',
  },
  es: {
    'app.tagline': 'sumérgete en sueños',
    'nav.sounds': 'Sonidos',
    'nav.mixes': 'Mezclas',
    'nav.breathe': 'Respirar',
    'nav.settings': 'Ajustes',
    'sounds.all': 'Todos',
    'cat.noise': 'Colores de ruido',
    'cat.rain': 'Lluvia y tormenta',
    'cat.water': 'Agua',
    'cat.nature': 'Naturaleza',
    'cat.wind': 'Viento',
    'cat.fire': 'Fuego',
    'cat.urban': 'Urbano',
    'cat.cosmos': 'Cosmos',
    'cat.baby': 'Sueño bebé',
    'cat.binaural': 'Binaurales',
    'player.playing': 'reproduciendo',
    'player.sound': 'sonido',
    'player.sounds': 'sonidos',
    'timer.title': 'Temporizador',
    'timer.fadeout': 'Desvanecimiento',
    'timer.cancel': 'Cancelar temporizador',
    'timer.fadingout': 'Desvaneciéndose en los últimos',
    'mixes.title': 'Mis mezclas',
    'mixes.save': 'Guardar actual',
    'mixes.saveCurrent': 'Guardar Mezcla Actual',
    'mixes.empty': 'No hay mezclas guardadas',
    'mixes.emptyHint': 'Reproduce sonidos y guarda tus combinaciones favoritas',
    'mixes.placeholder': 'Nombre de la mezcla...',
    'mixes.saveBtn': 'Guardar',
    'breathing.title': 'Respiración',
    'breathing.desc': 'Ejercicios de respiración guiada para relajarte y dormir.',
    'breathing.start': 'Iniciar',
    'breathing.stop': 'Detener',
    'breathing.back': 'Volver',
    'breathing.ready': 'Listo',
    'breathing.inhale': 'Inhalar',
    'breathing.hold': 'Sostener',
    'breathing.exhale': 'Exhalar',
    'breathing.cycles': 'ciclos completados',
    'breathing.cycle': 'ciclo completado',
    'breathing.478': '4-7-8 Relajación',
    'breathing.478.desc': 'Calma el sistema nervioso, promueve el sueño',
    'breathing.box': 'Respiración cuadrada',
    'breathing.box.desc': 'Reduce el estrés y la ansiedad',
    'breathing.simple': 'Calma simple',
    'breathing.simple.desc': 'Respiración fácil para principiantes',
    'breathing.coherent': 'Coherente',
    'breathing.coherent.desc': 'Coherencia corazón-cerebro a 6 resp/min',
    'breathing.session': 'Sesión',
    'breathing.minutes': 'minutos',
    'breathing.infinite': 'Infinito',
    'breathing.custom': 'Personalizado',
    'breathing.custom.desc': 'Establece tu ritmo',
    'breathing.complete': 'Sesión Completa',
    'breathing.totalTime': 'Tiempo total',
    'breathing.sounds': 'Sonido Ambiental',
    'breathing.silent': 'Silencio',
    'breathing.breatheIn': 'Inhala',
    'breathing.breatheOut': 'Exhala',
    'breathing.zenScene': 'Templo Zen',
    'breathing.warmScene': 'Deriva Cálida',
    'breathing.meditationScene': 'Meditación',
    'random.title': 'Mix Aleatorio',
    'random.count': 'Numero de sonidos',
    'random.volumeMin': 'Volumen minimo',
    'random.volumeMax': 'Volumen maximo',
    'random.categories': 'Categorias',
    'random.diversify': 'Categorias diferentes',
    'random.generate': 'Generar Mix',
    'random.presets': 'Presets Rápidos',
    'random.preset.deepSleep': 'Sueño Profundo',
    'random.preset.natureRelax': 'Naturaleza',
    'random.preset.focus': 'Enfoque',
    'random.preset.cozy': 'Acogedor',
    'random.enableAll': 'Activar Todas',
    'sounds.search': 'Buscar sonidos...',
    'sounds.noResults': 'No se encontraron sonidos',
    'sounds.favorites': 'Favoritos',
    'settings.binaural': 'Ritmos Binaurales',
    'settings.binaural.desc': 'Mostrar categoría de ritmos binaurales',
    'sounds.allSounds': 'Todos los sonidos',
    'exit.message': 'Estas seguro de que quieres salir de Somnio?',
    'exit.stay': 'Quedarme',
    'exit.leave': 'Salir',
    'start.timer': 'Iniciar temporizador',
    'settings.howToUse': 'Como usar',
    'howto.mix.title': 'Mezclar sonidos',
    'howto.mix.desc': 'Toca cualquier tarjeta para reproducir. Toca varias para mezclar sonidos.',
    'howto.volume.title': 'Ajustar volumen',
    'howto.volume.desc': 'Usa el deslizador vertical en la tarjeta, o toca el reproductor para el mezclador.',
    'howto.save.title': 'Guardar mezclas',
    'howto.save.desc': 'Toca el icono de marcador en el reproductor para guardar tu mezcla actual.',
    'howto.timer.title': 'Temporizador de sueno',
    'howto.timer.desc': 'Toca el reloj arriba a la derecha. Establece la duracion y los sonidos se apagaran automaticamente.',
    'howto.breathe.title': 'Ejercicios de respiracion',
    'howto.breathe.desc': 'Ve a la pestana Respirar. Elige un patron y sigue el circulo animado.',
    'howto.info.title': 'Info del sonido',
    'howto.info.desc': 'Toca "i" en cualquier tarjeta para ver detalles, consejos y ajustar volumen.',
    'howto.install.title': 'Instalar como app',
    'howto.install.desc.android': 'Android: Abre en Chrome > Menu (3 puntos) > "Instalar app" o "Agregar a pantalla de inicio".',
    'howto.install.desc.ios': 'iPhone: Abre en Safari > Boton Compartir > "Agregar a pantalla de inicio".',
    'settings.title': 'Ajustes',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.theme.dark': 'Oscuro',
    'settings.theme.midnight': 'Medianoche',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Océano',
    'settings.about': 'Acerca de',
    'settings.version': 'Versión',
    'settings.donate': 'Apoyar Somnio',
    'settings.donateDesc': 'Somnio es gratuito y abierto. Si te gusta, considera una donación.',
    'install': 'Instalar',
    'scenes.title': 'Escenas',
    'scene.zenTemple': 'Templo Zen',
    'scene.zenTemple.desc': 'Cuencos y campanas',
    'scene.rainyNight': 'Noche Lluviosa',
    'scene.rainyNight.desc': 'Lluvia con truenos lejanos',
    'scene.forestClearing': 'Claro del Bosque',
    'scene.forestClearing.desc': 'Insectos nocturnos y agua',
    'scene.cozyCabin': 'Cabana Acogedora',
    'scene.cozyCabin.desc': 'Chimenea con lluvia afuera',
    'scene.deepOcean': 'Oceano Profundo',
    'scene.deepOcean.desc': 'Ambiente submarino',
    'scene.warmDrift': 'Deriva Calida',
    'scene.warmDrift.desc': 'Ruido suave con campanillas',
    'scene.tibetanEvening': 'Tarde Tibetana',
    'scene.tibetanEvening.desc': 'Drone om con cuencos tibetanos',
    'scene.starfield': 'Campo Estelar',
    'scene.starfield.desc': 'Drones cosmicos y tonos etereos',
    'scene.meditation': 'Meditacion',
    'scene.meditation.desc': 'Drone om con cuencos y pad ambiental',
    'scene.cafeFocus': 'Cafe Enfoque',
    'scene.cafeFocus.desc': 'Ambiente de cafe con lluvia suave',
    'scene.nightTrain': 'Tren Nocturno',
    'scene.nightTrain.desc': 'Viaje en tren bajo la lluvia',
    'scene.beachSunset': 'Atardecer en Playa',
    'scene.beachSunset.desc': 'Olas del oceano con grillos al atardecer',
    'scene.candlelight': 'Luz de Vela',
    'scene.candlelight.desc': 'Chimenea calida con campanillas suaves',
    'scene.babySleep': 'Sueno de Bebe',
    'scene.babySleep.desc': 'Sonidos de utero con latidos del corazon',
  },
}

interface SettingsState {
  language: Language
  theme: ThemeMode
  binauralEnabled: boolean
  setLanguage: (lang: Language) => void
  setTheme: (theme: ThemeMode) => void
  setBinauralEnabled: (v: boolean) => void
  t: (key: string) => string
}

export const useSettingsStore = create<SettingsState>()(
  persist(
    (set, get) => ({
      language: 'en',
      theme: 'dark',
      binauralEnabled: false,
      setLanguage: (language: Language) => set({ language }),
      setTheme: (theme: ThemeMode) => {
        set({ theme })
        applyTheme(theme)
      },
      setBinauralEnabled: (binauralEnabled: boolean) => set({ binauralEnabled }),
      t: (key: string) => {
        const lang = get().language
        return translations[lang][key] ?? translations.en[key] ?? key
      },
    }),
    {
      name: 'somnio-settings',
      onRehydrateStorage: () => (state) => {
        if (state) applyTheme(state.theme)
      },
    }
  )
)

function applyTheme(mode: ThemeMode): void {
  const t = themes[mode]
  const root = document.documentElement
  root.style.setProperty('--bg-primary', t.bgPrimary)
  root.style.setProperty('--bg-secondary', t.bgSecondary)
  root.style.setProperty('--bg-card', t.bgCard)
  root.style.setProperty('--bg-card-hover', t.bgCardHover)
  root.style.setProperty('--bg-active', t.bgActive)
  root.style.setProperty('--accent', t.accent)
  root.style.setProperty('--accent-glow', t.accentGlow)
  root.style.setProperty('--accent-light', t.accentLight)
}
