import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'en' | 'ro' | 'ru' | 'es'
export type ThemeMode = 'dark' | 'midnight' | 'amoled' | 'ocean'

export interface ThemeColors {
  bgPrimary: string
  bgSecondary: string
  bgCard: string
  bgCardHover: string
  bgActive: string
  accent: string
  accentGlow: string
  accentLight: string
}

export const themes: Record<ThemeMode, ThemeColors> = {
  dark: {
    bgPrimary: '#0a0a1a',
    bgSecondary: '#111128',
    bgCard: '#181838',
    bgCardHover: '#1f1f48',
    bgActive: '#2a1a5e',
    accent: '#7c5cfc',
    accentGlow: 'rgba(124, 92, 252, 0.3)',
    accentLight: '#9d82ff',
  },
  midnight: {
    bgPrimary: '#0d1117',
    bgSecondary: '#161b22',
    bgCard: '#1c2333',
    bgCardHover: '#252d3d',
    bgActive: '#1a3a5c',
    accent: '#58a6ff',
    accentGlow: 'rgba(88, 166, 255, 0.3)',
    accentLight: '#79c0ff',
  },
  amoled: {
    bgPrimary: '#000000',
    bgSecondary: '#0a0a0a',
    bgCard: '#141414',
    bgCardHover: '#1e1e1e',
    bgActive: '#1a1a3a',
    accent: '#bb86fc',
    accentGlow: 'rgba(187, 134, 252, 0.3)',
    accentLight: '#d4a5ff',
  },
  ocean: {
    bgPrimary: '#0a1628',
    bgSecondary: '#0f1d32',
    bgCard: '#152640',
    bgCardHover: '#1c3050',
    bgActive: '#1a3d5c',
    accent: '#00b4d8',
    accentGlow: 'rgba(0, 180, 216, 0.3)',
    accentLight: '#48cae4',
  },
}

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.tagline': 'drift into dreams',
    'nav.sounds': 'Sounds',
    'nav.mixes': 'Mixes',
    'nav.breathe': 'Breathe',
    'nav.settings': 'Settings',
    'sounds.all': 'All',
    'cat.noise': 'Noise Colors',
    'cat.rain': 'Rain & Storm',
    'cat.water': 'Water',
    'cat.nature': 'Nature',
    'cat.wind': 'Wind',
    'cat.fire': 'Fire',
    'cat.urban': 'Urban',
    'cat.cosmos': 'Cosmos',
    'cat.baby': 'Baby Sleep',
    'cat.binaural': 'Binaural Beats',
    'player.playing': 'playing',
    'player.sound': 'sound',
    'player.sounds': 'sounds',
    'timer.title': 'Sleep Timer',
    'timer.fadeout': 'Fade out',
    'timer.cancel': 'Cancel Timer',
    'timer.fadingout': 'Fading out in the last',
    'mixes.title': 'My Mixes',
    'mixes.save': 'Save Current',
    'mixes.empty': 'No saved mixes yet',
    'mixes.emptyHint': 'Play some sounds and save your favorite combinations',
    'mixes.placeholder': 'Mix name...',
    'mixes.saveBtn': 'Save',
    'breathing.title': 'Breathing',
    'breathing.desc': 'Guided breathing exercises to help you relax and fall asleep.',
    'breathing.start': 'Start',
    'breathing.stop': 'Stop',
    'breathing.back': 'Back',
    'breathing.ready': 'Ready',
    'breathing.inhale': 'Inhale',
    'breathing.hold': 'Hold',
    'breathing.exhale': 'Exhale',
    'breathing.cycles': 'cycles completed',
    'breathing.cycle': 'cycle completed',
    'breathing.478': '4-7-8 Relaxing',
    'breathing.478.desc': 'Calms the nervous system, promotes sleep',
    'breathing.box': 'Box Breathing',
    'breathing.box.desc': 'Reduces stress and anxiety',
    'breathing.simple': 'Simple Calm',
    'breathing.simple.desc': 'Easy breathing for beginners',
    'breathing.coherent': 'Coherent',
    'breathing.coherent.desc': 'Heart-brain coherence at 6 breaths/min',
    'sounds.allSounds': 'All Sounds',
    'exit.message': 'Are you sure you want to leave Somnio?',
    'exit.stay': 'Stay',
    'exit.leave': 'Leave',
    'start.timer': 'Start Timer',
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.theme.dark': 'Dark',
    'settings.theme.midnight': 'Midnight',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Ocean',
    'settings.about': 'About',
    'settings.version': 'Version',
    'settings.donate': 'Support Somnio',
    'settings.donateDesc': 'Somnio is free and open. If you enjoy it, consider a donation.',
    'install': 'Install App',
  },
  ro: {
    'app.tagline': 'pluteste in vise',
    'nav.sounds': 'Sunete',
    'nav.mixes': 'Mix-uri',
    'nav.breathe': 'Respiratie',
    'nav.settings': 'Setari',
    'sounds.all': 'Toate',
    'cat.noise': 'Culori Zgomot',
    'cat.rain': 'Ploaie & Furtuna',
    'cat.water': 'Apa',
    'cat.nature': 'Natura',
    'cat.wind': 'Vant',
    'cat.fire': 'Foc',
    'cat.urban': 'Urban',
    'cat.cosmos': 'Cosmos',
    'cat.baby': 'Somn Bebelusi',
    'cat.binaural': 'Unde Binaurale',
    'player.playing': 'redam',
    'player.sound': 'sunet',
    'player.sounds': 'sunete',
    'timer.title': 'Timer Somn',
    'timer.fadeout': 'Diminuare',
    'timer.cancel': 'Anuleaza Timer',
    'timer.fadingout': 'Se diminueaza in ultimele',
    'mixes.title': 'Mix-urile Mele',
    'mixes.save': 'Salveaza',
    'mixes.empty': 'Niciun mix salvat',
    'mixes.emptyHint': 'Reda sunete si salveaza combinatiile preferate',
    'mixes.placeholder': 'Numele mix-ului...',
    'mixes.saveBtn': 'Salveaza',
    'breathing.title': 'Respiratie',
    'breathing.desc': 'Exercitii de respiratie ghidate pentru relaxare si adormire.',
    'breathing.start': 'Start',
    'breathing.stop': 'Stop',
    'breathing.back': 'Inapoi',
    'breathing.ready': 'Pregatit',
    'breathing.inhale': 'Inspira',
    'breathing.hold': 'Tine',
    'breathing.exhale': 'Expira',
    'breathing.cycles': 'cicluri completate',
    'breathing.cycle': 'ciclu completat',
    'breathing.478': '4-7-8 Relaxare',
    'breathing.478.desc': 'Calmeaza sistemul nervos, promoveaza somnul',
    'breathing.box': 'Respiratie Box',
    'breathing.box.desc': 'Reduce stresul si anxietatea',
    'breathing.simple': 'Calm Simplu',
    'breathing.simple.desc': 'Respiratie usoara pentru incepatori',
    'breathing.coherent': 'Coherenta',
    'breathing.coherent.desc': 'Coherenta inima-creier la 6 respiratii/min',
    'sounds.allSounds': 'Toate Sunetele',
    'exit.message': 'Esti sigur ca vrei sa parasesti Somnio?',
    'exit.stay': 'Raman',
    'exit.leave': 'Ies',
    'start.timer': 'Porneste Timer',
    'settings.title': 'Setari',
    'settings.language': 'Limba',
    'settings.theme': 'Tema',
    'settings.theme.dark': 'Intuneric',
    'settings.theme.midnight': 'Miezul Noptii',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Ocean',
    'settings.about': 'Despre',
    'settings.version': 'Versiune',
    'settings.donate': 'Sustine Somnio',
    'settings.donateDesc': 'Somnio e gratuit si deschis. Daca iti place, considera o donatie.',
    'install': 'Instaleaza',
  },
  ru: {
    'app.tagline': 'погрузись в сны',
    'nav.sounds': 'Звуки',
    'nav.mixes': 'Миксы',
    'nav.breathe': 'Дыхание',
    'nav.settings': 'Настройки',
    'sounds.all': 'Все',
    'cat.noise': 'Цвета шума',
    'cat.rain': 'Дождь и гроза',
    'cat.water': 'Вода',
    'cat.nature': 'Природа',
    'cat.wind': 'Ветер',
    'cat.fire': 'Огонь',
    'cat.urban': 'Город',
    'cat.cosmos': 'Космос',
    'cat.baby': 'Сон малыша',
    'cat.binaural': 'Бинауральные',
    'player.playing': 'воспроизводится',
    'player.sound': 'звук',
    'player.sounds': 'звуков',
    'timer.title': 'Таймер сна',
    'timer.fadeout': 'Затухание',
    'timer.cancel': 'Отменить таймер',
    'timer.fadingout': 'Затухание в последние',
    'mixes.title': 'Мои миксы',
    'mixes.save': 'Сохранить',
    'mixes.empty': 'Нет сохранённых миксов',
    'mixes.emptyHint': 'Включите звуки и сохраните любимые комбинации',
    'mixes.placeholder': 'Название микса...',
    'mixes.saveBtn': 'Сохранить',
    'breathing.title': 'Дыхание',
    'breathing.desc': 'Дыхательные упражнения для расслабления и засыпания.',
    'breathing.start': 'Старт',
    'breathing.stop': 'Стоп',
    'breathing.back': 'Назад',
    'breathing.ready': 'Готов',
    'breathing.inhale': 'Вдох',
    'breathing.hold': 'Задержка',
    'breathing.exhale': 'Выдох',
    'breathing.cycles': 'циклов завершено',
    'breathing.cycle': 'цикл завершён',
    'breathing.478': '4-7-8 Расслабление',
    'breathing.478.desc': 'Успокаивает нервную систему, помогает уснуть',
    'breathing.box': 'Квадратное дыхание',
    'breathing.box.desc': 'Снижает стресс и тревогу',
    'breathing.simple': 'Простое спокойствие',
    'breathing.simple.desc': 'Лёгкое дыхание для начинающих',
    'breathing.coherent': 'Когерентное',
    'breathing.coherent.desc': 'Когерентность сердце-мозг при 6 вдохах/мин',
    'sounds.allSounds': 'Все звуки',
    'exit.message': 'Вы уверены, что хотите выйти из Somnio?',
    'exit.stay': 'Остаться',
    'exit.leave': 'Выйти',
    'start.timer': 'Запустить таймер',
    'settings.title': 'Настройки',
    'settings.language': 'Язык',
    'settings.theme': 'Тема',
    'settings.theme.dark': 'Тёмная',
    'settings.theme.midnight': 'Полночь',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Океан',
    'settings.about': 'О приложении',
    'settings.version': 'Версия',
    'settings.donate': 'Поддержать Somnio',
    'settings.donateDesc': 'Somnio бесплатен и открыт. Если нравится, поддержите донатом.',
    'install': 'Установить',
  },
  es: {
    'app.tagline': 'sumérgete en sueños',
    'nav.sounds': 'Sonidos',
    'nav.mixes': 'Mezclas',
    'nav.breathe': 'Respirar',
    'nav.settings': 'Ajustes',
    'sounds.all': 'Todos',
    'cat.noise': 'Colores de ruido',
    'cat.rain': 'Lluvia y tormenta',
    'cat.water': 'Agua',
    'cat.nature': 'Naturaleza',
    'cat.wind': 'Viento',
    'cat.fire': 'Fuego',
    'cat.urban': 'Urbano',
    'cat.cosmos': 'Cosmos',
    'cat.baby': 'Sueño bebé',
    'cat.binaural': 'Binaurales',
    'player.playing': 'reproduciendo',
    'player.sound': 'sonido',
    'player.sounds': 'sonidos',
    'timer.title': 'Temporizador',
    'timer.fadeout': 'Desvanecimiento',
    'timer.cancel': 'Cancelar temporizador',
    'timer.fadingout': 'Desvaneciéndose en los últimos',
    'mixes.title': 'Mis mezclas',
    'mixes.save': 'Guardar actual',
    'mixes.empty': 'No hay mezclas guardadas',
    'mixes.emptyHint': 'Reproduce sonidos y guarda tus combinaciones favoritas',
    'mixes.placeholder': 'Nombre de la mezcla...',
    'mixes.saveBtn': 'Guardar',
    'breathing.title': 'Respiración',
    'breathing.desc': 'Ejercicios de respiración guiada para relajarte y dormir.',
    'breathing.start': 'Iniciar',
    'breathing.stop': 'Detener',
    'breathing.back': 'Volver',
    'breathing.ready': 'Listo',
    'breathing.inhale': 'Inhalar',
    'breathing.hold': 'Sostener',
    'breathing.exhale': 'Exhalar',
    'breathing.cycles': 'ciclos completados',
    'breathing.cycle': 'ciclo completado',
    'breathing.478': '4-7-8 Relajación',
    'breathing.478.desc': 'Calma el sistema nervioso, promueve el sueño',
    'breathing.box': 'Respiración cuadrada',
    'breathing.box.desc': 'Reduce el estrés y la ansiedad',
    'breathing.simple': 'Calma simple',
    'breathing.simple.desc': 'Respiración fácil para principiantes',
    'breathing.coherent': 'Coherente',
    'breathing.coherent.desc': 'Coherencia corazón-cerebro a 6 resp/min',
    'sounds.allSounds': 'Todos los sonidos',
    'exit.message': 'Estas seguro de que quieres salir de Somnio?',
    'exit.stay': 'Quedarme',
    'exit.leave': 'Salir',
    'start.timer': 'Iniciar temporizador',
    'settings.title': 'Ajustes',
    'settings.language': 'Idioma',
    'settings.theme': 'Tema',
    'settings.theme.dark': 'Oscuro',
    'settings.theme.midnight': 'Medianoche',
    'settings.theme.amoled': 'AMOLED',
    'settings.theme.ocean': 'Océano',
    'settings.about': 'Acerca de',
    'settings.version': 'Versión',
    'settings.donate': 'Apoyar Somnio',
    'settings.donateDesc': 'Somnio es gratuito y abierto. Si te gusta, considera una donación.',
    'install': 'Instalar',
  },
}

interface SettingsState {
  language: Language
  theme: ThemeMode
  setLanguage: (lang: Language) => void
  setTheme: (theme: ThemeMode) => void
  t: (key: string) => string
}

export const useSettingsStore = create<SettingsState>()(
  persist(
    (set, get) => ({
      language: 'en',
      theme: 'dark',
      setLanguage: (language: Language) => set({ language }),
      setTheme: (theme: ThemeMode) => {
        set({ theme })
        applyTheme(theme)
      },
      t: (key: string) => {
        const lang = get().language
        return translations[lang][key] ?? translations.en[key] ?? key
      },
    }),
    {
      name: 'somnio-settings',
      onRehydrateStorage: () => (state) => {
        if (state) applyTheme(state.theme)
      },
    }
  )
)

function applyTheme(mode: ThemeMode): void {
  const t = themes[mode]
  const root = document.documentElement
  root.style.setProperty('--bg-primary', t.bgPrimary)
  root.style.setProperty('--bg-secondary', t.bgSecondary)
  root.style.setProperty('--bg-card', t.bgCard)
  root.style.setProperty('--bg-card-hover', t.bgCardHover)
  root.style.setProperty('--bg-active', t.bgActive)
  root.style.setProperty('--accent', t.accent)
  root.style.setProperty('--accent-glow', t.accentGlow)
  root.style.setProperty('--accent-light', t.accentLight)
}
